export const PRODUCTS = [
  {
    id: "1",
    name: "JORDAN",
    manifactor: "JUMPMAN 2021 PF",
    stars: 3,
    price: 144,
    colors: ["red", "green", "black"],
  },
  {
    id: "2",
    name: "JORDAN",
    manifactor: "JUMPMAN 2021 PF",
    stars: 3,
    price: 44,
    colors: ["red", "blue"],
  },
  {
    id: "3",
    name: "JORDAN",
    manifactor: "JUMPMAN 2021 PF",
    stars: 3,
    price: 44,
    colors: ["red", "black"],
  },
  {
    id: "4",
    name: "JORDAN",
    manifactor: "JUMPMAN 2021 PF",
    stars: 3,
    price: 44,
    colors: ["red", "green", "black"],
  },
  {
    id: "5",
    name: "JORDAN",
    manifactor: "JUMPMAN 2021 PF",
    stars: 3,
    price: 44,
    colors: ["blue", "red"],
  },
  {
    id: "6",
    name: "JORDAN",
    manifactor: "JUMPMAN 2021 PF",
    stars: 3,
    price: 44,
    colors: ["red", "white"],
  },
  {
    id: "7",
    name: "JORDAN",
    manifactor: "JUMPMAN 2021 PF",
    stars: 3,
    price: 44,
    colors: ["black", "white"],
  },
  {
    id: "8",
    name: "JORDAN",
    manifactor: "JUMPMAN 2021 PF",
    stars: 3,
    price: 44,
    colors: ["blue", "green", "grey", "brown"],
  },
  {
    id: "9",
    name: "JORDAN",
    manifactor: "JUMPMAN 2021 PF",
    stars: 3,
    price: 44,
    colors: ["white"],
  },
];
