export const PRODUCTS = [
  {
    id: "1",
    name: "jumpman 2021 pf",
    manifactor: "jordan",
    stars: 4,
    price: 1200,
    colors: ["red", "green", "black"],
  },
  {
    id: "2",
    name: "air jordan I",
    manifactor: "jordan",
    stars: 5,
    price: 85,
    colors: ["red", "black", "purple", "gradient"],
  },
  {
    id: "3",
    name: "air jordan II",
    manifactor: "jordan",
    stars: 3,
    price: 79.99,
    colors: ["white", "red", "orange"],
  },
  {
    id: "4",
    name: "air jordan III",
    manifactor: "jordan",
    stars: 4,
    price: 49.99,
    colors: ["white", "black", "orange"],
  },
  {
    id: "5",
    name: "air jordan IV",
    manifactor: "jordan",
    stars: 3,
    price: 49.99,
    colors: ["black", "white", "red"],
  },
  {
    id: "6",
    name: "air jordan V",
    manifactor: "jordan",
    stars: 1,
    price: 29.99,
    colors: ["white"],
  },
  {
    id: "7",
    name: "air jordan VI",
    manifactor: "jordan",
    stars: 4,
    price: 99.99,
    colors: ["black", "white"],
  },
  {
    id: "8",
    name: "air jordan VI",
    manifactor: "jordan",
    stars: 2,
    price: 100,
    colors: ["red", "blue", "orange", "green", "white"],
  },
  {
    id: "9",
    name: "air jordan IX",
    manifactor: "jordan",
    stars: 5,
    price: 3400,
    colors: ["black", "golden"],
  },
];
