export const PRODUCTS = [
  {
    id: "1",
    stars: 4,
    price: 1200,
    manifactor: "jordan",
    name: "jumpman 2021 pf",
    colors: ["red", "green", "black"],
    sizes: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
    details: [
      { header: "type", value: "sneaker" },
      { header: "material", value: "cloth" },
      { header: "wayToWearShoes", value: "Stretchy" },
    ],
    comments: [
      {
        stars: 5,
        name: "vito",
        time: 1657033416137,
        suggested: false,
        text: "LOREM IADF ALORE ML O ADH UADHUF HAH UDH UAHUDHF UAH HUDFHU AHD  UHFI AUS DFJKOE ",
      },
    ],
  },

  // {
  //   id: "2",
  //   name: "air jordan I",
  //   manifactor: "jordan",
  //   stars: 5,
  //   price: 85,
  //   colors: ["red", "black", "purple", "gradient"],
  // },
  // {
  //   id: "3",
  //   name: "air jordan II",
  //   manifactor: "jordan",
  //   stars: 3,
  //   price: 79.99,
  //   colors: ["white", "red", "orange"],
  // },
  // {
  //   id: "4",
  //   name: "air jordan III",
  //   manifactor: "jordan",
  //   stars: 4,
  //   price: 49.99,
  //   colors: ["white", "black", "orange"],
  // },
  // {
  //   id: "5",
  //   name: "air jordan IV",
  //   manifactor: "jordan",
  //   stars: 3,
  //   price: 49.99,
  //   colors: ["black", "white", "red"],
  // },
  // {
  //   id: "6",
  //   name: "air jordan V",
  //   manifactor: "jordan",
  //   stars: 1,
  //   price: 29.99,
  //   colors: ["white"],
  // },
  // {
  //   id: "7",
  //   name: "air jordan VI",
  //   manifactor: "jordan",
  //   stars: 4,
  //   price: 99.99,
  //   colors: ["black", "white"],
  // },
  // {
  //   id: "8",
  //   name: "air jordan VI",
  //   manifactor: "jordan",
  //   stars: 2,
  //   price: 100,
  //   colors: ["red", "blue", "orange", "green", "white"],
  // },
  // {
  //   id: "9",
  //   name: "air jordan IX",
  //   manifactor: "jordan",
  //   stars: 5,
  //   price: 3400,
  //   colors: ["black", "golden"],
  // },
];
