export const PRODUCTS = [
  {
    comments: [],
    name: "Jump man pf",
    manifactor: "Jordan",
    details: [
      { header: "type", value: "sneaker" },
      { header: "material", value: "Cloth" },
      { header: "way to wear", value: "stregy" },
    ],
    price: "1400",
    sizes: [43, 43],
    stars: 4,
    colors: ["red", "white"],
  },
  {
    id: "2",
    name: "air jordan i",
    manifactor: "Jordan",
    stars: 0,
    price: 85,
    newPrice: "60",
    comments: [],
    colors: ["red", "white"],
    details: [
      { header: "type", value: "sneakers" },
      { header: "material", value: "Cloth" },
      { header: "way to wear", value: "strategy" },
    ],
    sizes: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: "3",
    name: "air jordan ii",
    manifactor: "Jordan",
    stars: 0,
    price: 35,
    comments: [],
    colors: ["red", "white", "orange", "blue", "green"],
    details: [
      { header: "type", value: "sneakers" },
      { header: "material", value: "Cloth" },
      { header: "way to wear", value: "strategy" },
    ],
    sizes: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: "4",
    name: "air jordan iv",
    manifactor: "Jordan",
    stars: 0,
    price: 90,
    comments: [],
    colors: ["black", "white"],
    details: [
      { header: "type", value: "sneakers" },
      { header: "material", value: "Cloth" },
      { header: "way to wear", value: "strategy" },
    ],
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: "5",
    name: "air jordan v",
    manifactor: "Jordan",
    stars: 0,
    price: 59.9,
    comments: [],
    colors: ["black", "red", "white"],
    details: [
      { header: "type", value: "sneakers" },
      { header: "material", value: "Cloth" },
      { header: "way to wear", value: "strategy" },
    ],
    sizes: [32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: "6",
    name: "air jordan vi",
    manifactor: "Jordan",
    stars: 0,
    price: 99.9,
    newPrice: "150",
    comments: [],
    colors: ["black"],
    details: [
      { header: "type", value: "sneakers" },
      { header: "material", value: "Cloth" },
      { header: "way to wear", value: "strategy" },
    ],
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: "7",
    name: "air jordan vii",
    manifactor: "Jordan",
    stars: 0,
    price: 50,
    comments: [],
    colors: ["green", "grey", "red", "orange"],
    details: [
      { header: "type", value: "sneakers" },
      { header: "material", value: "Cloth" },
      { header: "way to wear", value: "strategy" },
    ],
    sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: "8",
    name: "air jordan viii",
    manifactor: "Jordan",
    stars: 0,
    price: 49.9,
    newPrice: "80",
    comments: [],
    colors: ["red", "white"],
    details: [
      { header: "type", value: "sneakers" },
      { header: "material", value: "Cloth" },
      { header: "way to wear", value: "strategy" },
    ],
    sizes: [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: "9",
    name: "air jordan ix",
    manifactor: "Jordan",
    stars: 0,
    price: 3400,
    comments: [],
    colors: ["golden"],
    details: [
      { header: "type", value: "sneakers" },
      { header: "material", value: "Cloth" },
      { header: "way to wear", value: "strategy" },
    ],
    sizes: [37, 38, 39, 40, 41, 42, 43, 44],
  },
];
